version: '3'
services:
  ocrmypdf-watchdog:
    container_name: OCRmyPDF
    network_mode: none
    # image: darthbermel/ocrmypdf-watchdog:latest
    build: '.'
    restart: always
    environment:
      OCRMYPDF_IN: /in
      OCRMYPDF_OUT: /out
      WATCHDOG_FREQUENCY: 1
      WATCHDOG_EXTENSIONS: pdf,jpg,jpeg,tif,tiff,png,gif
      OCRMYPDF_BINARY: ocrmypdf
      OCRMYPDF_PARAMETER: -l eng+fra+deu+nld --rotate-pages --deskew --jobs 4 --output-type pdfa
    volumes:
    - ./in:/in
    - ./out:/out
